### ISSUE TITLE
It failed Why. Plz help me

### ISSUE THREAD

**Issue by Reus2Tech** [ProAppleOS/Upgrade-from-10.3.x-to-iOS-11.1.2-on-any-64Bit-device-with-Blobs#3]
I followed your instruction step by step 
but did't work 
Why?

Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152
Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44
Odysseus Support: yes
INFO: device serial number is FK1V9739HFLW
[INFO] 64bit device detected
futurerestore init done
reading ticket blob.shsh2 done
user specified to use latest signed sep
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest iOS: 11.2.1
[TSSC] got firmwareurl for iOS 11.2.1 build 15C153
100 [================================================================================================003 [==>                                                                                             015 [==============>                                                                                 027 [==========================>                                                                     033 [================================>                                                               039 [======================================>                                                         045 [============================================>                                                   051 [==================================================>                                             057 [========================================================>                                       063 [==============================================================>                                 069 [====================================================================>                           076 [===========================================================================>                    082 [=================================================================================>              094 [=============================================================================================>  100 [===================================================================================================>]
[Error] [TSSR] cant find boardconfig for device=iPhone8,1 please manuall use --boardconfig
[Error] could not get SEP path
[Error] Fail code=-31
Failed with errorcode=-31

**Comment by ProAppleOS** [comment]
You have 6s so you need to specify your boardconfig. 
Your sep path is wrong 
		
		

		
	




On Tue, Dec 26, 2017 at 1:05 PM +0100, "Reus2Tech" <notifications@github.com> wrote:












I followed your instruction step by step

but did't work

Why?


Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152

Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44

Odysseus Support: yes

INFO: device serial number is FK1V9739HFLW

[INFO] 64bit device detected

futurerestore init done

reading ticket blob.shsh2 done

user specified to use latest signed sep

[TSSC] opening firmware.json

[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed

[TSSC] selecting latest iOS: 11.2.1

[TSSC] got firmwareurl for iOS 11.2.1 build 15C153

100 [================================================================================================003 [==>                                                                                             015 [==============>                                                                                 027 [==========================>                                                                     033 [================================>                                                               039 [======================================>                                                         045 [============================================>                                                   051 [==================================================>                                             057 [========================================================>                                       063 [==============================================================>                                 069 [====================================================================>                           076 [===========================================================================>                    082 [=================================================================================>              094 [=============================================================================================>  100 [===================================================================================================>]

[Error] [TSSR] cant find boardconfig for device=iPhone8,1 please manuall use --boardconfig

[Error] could not get SEP path

[Error] Fail code=-31

Failed with errorcode=-31
